[project]
name = "sql-alchemy-ls10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Romanenko Yliia(mac)", email = "romany0507306677@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "livereload>=2.7.1",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
sql-alchemy-ls10 = "sql_alchemy_ls10:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
